/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VansIdRouteImport } from './routes/vans/$id'

const VansIndexLazyRouteImport = createFileRoute('/vans/')()
const VansTypeLazyRouteImport = createFileRoute('/vans/$type')()

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VansIndexLazyRoute = VansIndexLazyRouteImport.update({
  id: '/vans/',
  path: '/vans/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/vans/index.lazy').then((d) => d.Route))
const VansTypeLazyRoute = VansTypeLazyRouteImport.update({
  id: '/vans/$type',
  path: '/vans/$type',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/vans/$type.lazy').then((d) => d.Route))
const VansIdRoute = VansIdRouteImport.update({
  id: '/vans/$id',
  path: '/vans/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/vans/$id': typeof VansIdRoute
  '/vans/$type': typeof VansTypeLazyRoute
  '/vans': typeof VansIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/vans/$id': typeof VansIdRoute
  '/vans/$type': typeof VansTypeLazyRoute
  '/vans': typeof VansIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/vans/$id': typeof VansIdRoute
  '/vans/$type': typeof VansTypeLazyRoute
  '/vans/': typeof VansIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/vans/$id' | '/vans/$type' | '/vans'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/vans/$id' | '/vans/$type' | '/vans'
  id: '__root__' | '/' | '/about' | '/vans/$id' | '/vans/$type' | '/vans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  VansIdRoute: typeof VansIdRoute
  VansTypeLazyRoute: typeof VansTypeLazyRoute
  VansIndexLazyRoute: typeof VansIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vans/': {
      id: '/vans/'
      path: '/vans'
      fullPath: '/vans'
      preLoaderRoute: typeof VansIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vans/$type': {
      id: '/vans/$type'
      path: '/vans/$type'
      fullPath: '/vans/$type'
      preLoaderRoute: typeof VansTypeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vans/$id': {
      id: '/vans/$id'
      path: '/vans/$id'
      fullPath: '/vans/$id'
      preLoaderRoute: typeof VansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  VansIdRoute: VansIdRoute,
  VansTypeLazyRoute: VansTypeLazyRoute,
  VansIndexLazyRoute: VansIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
